# use the latest ubuntu distro
dist: trusty
# require sudo
sudo: required

# this is a node project
language: node_js
node_js:
- '6'

compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake

# proxy reset for tests
env:
  - http_proxy=''
  - HTTP_PROXY=''

git:
  submodules: false

before_install:
  # init the plugins / submodules
  # - git submodule update --init
  # install alsa stuff
  ## - sudo apt-get install libasound2-dev
  # Link gcc-6 and g++-6 to their standard commands
  ## - sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
  ## - sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++
  # Export CC and CXX to tell cmake which compiler to use
  ## - export CC=/usr/bin/gcc-6
  ## - export CXX=/usr/bin/g++-6
  # Check versions of gcc, g++ and cmake
  ## - gcc -v && g++ -v && cmake --version

  #prepare for node-gyp
  ## - sudo apt-get install build-essential node-gyp

  # Run actual build commands next
  ## - npm install -g gulp@3.9.1
install:
  - npm install
script:
  - npm run build
